[domain-scan]
service-names = [
    '^domain-scan',
]

    [[domain-scan.scan]]
        name = 'spiderfoot-email'
        command = '/usr/bin/spiderfoot -t EMAILADDR,EMAILADDR_COMPROMISED,EMAILADDR_DELIVERABLE,EMAILADDR_GENERIC,MALICIOUS_EMAILADDR -x -q -r -s {address} | tee "{scandir}/info/email_spiderfoot_{address}.ansi"'
        run_once = true
        [[domain-scan.scan.pattern]]
            description = 'Email: {match}'
            pattern = '[\w.+-]+@[\w-]+\.[\w.-]+'
    
    [[domain-scan.scan]]
        name = 'ipapi-geolocation'
        command = '/usr/bin/curl  http://ip-api.com/json/{address} | tee "{scandir}/info/geolocation_ipapi_{address}.json"'
        run_once = true
        [[domain-scan.scan.pattern]]
            description = ' GeoInfo: {match}'
            pattern = '"country"\s*:\s*"([^"]+)"'

        [[domain-scan.scan.pattern]]
            description = ' GeoInfo: {match}'
            pattern = '"city"\s*:\s*"([^"]+)"'

        [[domain-scan.scan.pattern]]
            description = ' GeoInfo: {match}'
            pattern = '"isp"\s*:\s*"([^"]+)"'

        [[domain-scan.scan.pattern]]
            description = ' GeoInfo: {match}'
            pattern = '"as"\s*:\s*"([^"]+)"'

    [[domain-scan.scan]]
        name = 'sublist3r-ports'
        command = '/usr/bin/sublist3r --verbose --no-color --ports 21,22,23,25,53,80,110,111,135,139,143,199,443,445,587,993,995,1025,1720,1723,3306,3389,5900,8080,8888 --domain {address} -o "{scandir}/recon/subdomains_sublist3r_{address}.txt"'
        run_once = true
        [[domain-scan.scan.pattern]]
            description = 'TCPPorts: {match}'
            pattern = '(.*Found open ports:.*)'
        

    [[domain-scan.scan]]
    name = 'asn-net'
    command = '/usr/bin/asn -s -m -J {ipaddress} | tee "{scandir}/tech/net_asn_{ipaddress}.json"'
        [[domain-scan.scan.pattern]]
            description = 'Tech: {match}'
            pattern = 'cpe:(?:/a:)?(.*)$'
        [[domain-scan.scan.pattern]]
            description = 'CVE: {match}'
            pattern = '(CVE-\d{4}-\d{4,7})'
    
    [[domain-scan.scan]]
        name = 'spiderfoot-web'
        command = '/usr/bin/spiderfoot -t WEBSERVER_BANNER,WEBSERVER_TECHNOLOGY,WEB_ANALYTICS_ID,TARGET_WEB_CONTENT_TYPE,TARGET_WEB_COOKIE -f -x -q -r -s {address} -o csv | tee "{scandir}/tech/web_spiderfoot_{domain}.ansi"'
        run_once = true
        [[domain-scan.pattern]]
            description = 'WebTech: {match}'
            pattern = '.*,Web Server,(\S+),((?!text/html|text/css).*)'
        [[domain-scan.scan.pattern]]
            description = 'WebTech: {match}'
            pattern = '.*,Web Content Type,(\S+),((?!text/html|text/css).*)'

    [[domain-scan.scan]]
        name = 'dnsrecon-dnsenum'
        command = '/usr/bin/dnsrecon -a -b -d {address} -j "{scandir}/recon/dns_dnsrecon_{address}.json"'
        run_once = true
        [[domain-scan.scan.pattern]]
            description = 'DNSEnum: {match}'
            pattern = '([ \t ]NS\s.*\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
        [[domain-scan.scan.pattern]]
            description = 'DNSEnum: {match}'
            pattern = '([ \t ]A\s.*\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
        [[domain-scan.scan.pattern]]
            description = 'DNSEnum: {match}'
            pattern = '([ \t ]MX\s.*\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
        [[domain-scan.scan.pattern]]
            description = 'DNSEnum: {match}'
            pattern = '([ \t ]SOA\s.*\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
        [[domain-scan.scan.pattern]]
            description = 'DNSEnum: {match}'
            pattern = '([ \t ]TXT\s.*\sv=spf.*)'
        [[domain-scan.scan.pattern]]
            description = 'DNSEnum: {match}'
            pattern = '([ \t ]TXT\s.*\sv=spf.*)'
        [[domain-scan.scan.pattern]]
            description = 'DNSEnum: {match}'
            pattern = '([ \t ]TXT\s.*\sv=DMAR.*)'
        [[domain-scan.scan.pattern]]
            description = 'DNSEnum: {match}'
            pattern = '([ \t ]PTR\s.*\s\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'

   
    [[domain-scan.scan]]
        name = 'spiderfoot-dataleak'
        command = '/usr/bin/spiderfoot -m sfp_ahmia,sfp_stackoverflow,sfp_slideshare,sfp_searchcode,sfp_opencorporates,sfp_openbugbounty,sfp_malwarepatrol,sfp_darksearch,sfp_dehashed -q -r -s {address} -o csv | tee "{scandir}/info/dataleak_spipderfoot_{address}.ansi"'
        run_once = true
        [[domain-scan.scan.pattern]]
            description = 'Dataleak: {match}'
            pattern = '.*,([^,]+,(?!.*Data).*)$'

    [[domain-scan.scan]]
        name = 'spiderfoot-socialmedia'
        command = '/usr/bin/spiderfoot -m sfp_socialprofiles,sfp_sociallinks,sfp_social,sfp_psbdmp,sfp_instagram,sfp_flickr,sfp_azureblobstorage,sfp_apple_itunes,sfp_arin,sfp_accounts -q -r -s {address} -o csv | tee "{scandir}/info/dataleak_spipderfoot_{address}.ansi"'
        run_once = true
        [[domain-scan.scan.pattern]]
            description = 'Dataleak: {match}'
            pattern = '.*,([^,]+,(?!.*Data).*)$'

    [[domain-scan.scan]]
        name = 'metadata-collector'
        command = '/usr/bin/metagoofil -e 45 -i 5 -l 10 -n 25 -t "xlsx,pdf,docx,pptx,conf,config,ppt,doc,xls" -d {address} -f="{scandir}/info/dataleak_metagoofil_{address}.txt" -o "{scandir}/info/" | tee "{scandir}/info/metadata_metagoogil.ansi"'
        run_once = true
        [[domain-scan.scan.pattern]]
            description = 'Metadata: {match}'
            pattern = '(.*Results: .*)' 
        
    [[domain-scan.manual]]
    description = 'dnsrecon-dnsspoofing'
    commands = [
            '/usr/bin/dnsrecon -a -b -d {address} -t zonewalk -j "{scandir}/info/dnspoof_dnsrecon_{address}.json"'
    ]

    [[domain-scan.manual]]
    description = 'TheHarvester-all'
    commands = [
            'theHarvester -d {address} --virtual-host -b all -l 250 --start 0 | tee "{scandir}/info/full_theharvester_{address}.ansi"'
    ]

    [[domain-scan.manual]]
    description = 'InfoHound-All -> https://github.com/Fundacio-i2CAT/InfoHound.git'
    commands = [
            'Change on ./infohound_project/settings.py => ALLOWED_HOSTS = ["0.0.0.0","127.0.0.1"]'
    ]
    
[ip-subdomain]
service-names = [
    '^ip-subdomain',
]

[[ip-subdomain.scan]]
        name = 'ipapi-geolocation'
        command = '/usr/bin/curl  http://ip-api.com/json/{ipaddress} | tee "{scandir}/info/geolocation_ipapi_{ipaddress}.json"'
        [[ip-subdomain.scan.pattern]]
            description = ' GeoInfo: {match}'
            pattern = '"country"\s*:\s*"([^"]+)"'

        [[ip-subdomain.scan.pattern]]
            description = ' GeoInfo: {match}'
            pattern = '"city"\s*:\s*"([^"]+)"'

        [[ip-subdomain.scan.pattern]]
            description = ' GeoInfo: {match}'
            pattern = '"isp"\s*:\s*"([^"]+)"'

        [[ip-subdomain.scan.pattern]]
            description = ' GeoInfo: {match}'
            pattern = '"as"\s*:\s*"([^"]+)"'

    [[ip-subdomain.scan]]
        name = 'sublist3r-ports'
        command = '/usr/bin/sublist3r --verbose --no-color --ports 21,22,23,25,53,80,110,111,135,139,143,199,443,445,587,993,995,1025,1720,1723,3306,3389,5900,8080,8888 --domain {ipaddress} -o "{scandir}/recon/subdomains_sublist3r_{ipaddress}.txt"'
        [[ip-subdomain.scan.pattern]]
            description = 'TCPPorts: {match}'
            pattern = '(.*Found open ports:.*)'

    [[ip-subdomain.scan]]
    name = 'spiderfoot-web'
    command = '/usr/bin/spiderfoot -t WEBSERVER_BANNER,WEBSERVER_TECHNOLOGY,WEB_ANALYTICS_ID,TARGET_WEB_CONTENT_TYPE,TARGET_WEB_COOKIE -f -x -q -r -s {domain} -o csv | tee "{scandir}/tech/web_spiderfoot_{domain}.ansi"'
        [[ip-subdomain.scan.pattern]]
            description = 'WebTech: {match}'
            pattern = '.*,Web Server,(\S+),((?!text/html|text/css).*)'
        [[ip-subdomain.scan.pattern]]
            description = 'WebTech: {match}'
            pattern = '.*,Web Content Type,(\S+),((?!text/html|text/css).*)'

    [[ip-subdomain.scan]]
    name = 'asn-net'
    command = '/usr/bin/asn -s -m -J {ipaddress} | tee "{scandir}/tech/net_asn_{ipaddress}.json"'
        [[ip-subdomain.scan.pattern]]
            description = 'Tech: {match}'
            pattern = 'cpe:(?:/a:)?(.*)$'
        [[ip-subdomain.scan.pattern]]
            description = 'CVE: {match}'
            pattern = '(CVE-\d{4}-\d{4,7})' 
       
    [[ip-subdomain.manual]]
    description = 'ipgeolocation -> https://github.com/maldevel/IPGeoLocation.git'
    commands = [
            'python3 ipgeolocation.py -t {ipaddress} -ec "{scandir}/info/ip_geolocation_{ipaddress}.csv"'
    ]
        

[subdomain-recon]
service-names = [
    '^subdomain-recon',
]
    [[subdomain-recon.scan]]
    name = 'spiderfoot-web'
    command = '/usr/bin/spiderfoot -t WEBSERVER_BANNER,WEBSERVER_TECHNOLOGY,WEB_ANALYTICS_ID,TARGET_WEB_CONTENT_TYPE,TARGET_WEB_COOKIE -f -x -q -r -s {domain} -o csv | tee "{scandir}/tech/web_spiderfoot_{domain}.ansi"'
        [[subdomain-recon.scan.pattern]]
            description = 'WebTech: {match}'
            pattern = '.*,Web Server,(\S+),((?!text/html|text/css).*)'
        [[subdomain-recon.scan.pattern]]
            description = 'WebTech: {match}'
            pattern = '.*,Web Content Type,(\S+),((?!text/html|text/css).*)'
      