[domain]
    [domain.host-domain]
        command = 'host {address} | tee "{scandir}/recon/dns_host_{address}.ansi"'
        pattern = '^(?P<domain>[a-zA-Z0-9.-]+)(\s*)(has)(\s*)(address)(\s*)(?P<ipaddress>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
       
    [domain.dig-revdns-domain]
        command = '/usr/bin/dig {address} | tee "{scandir}/recon/revdns_dig_{address}.ansi"'
        pattern = '^(?P<domain>[a-zA-Z0-9.-]+)(\.)(\s*)(.*)(\\t)(?P<ipaddress>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'

    [domain.dnsrecon-revdns-domain]
        command = '/usr/bin/dnsrecon -a -b -d {address} -c "{scandir}/recon/revdns_dnsrecon_{address}.csv"'
        pattern = ',(?P<domain>[a-zA-Z0-9.-]+),(?P<ipaddress>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}),'

    [domain.sublist3r-subdomains]
        command = '/usr/bin/sublist3r --verbose --no-color --domain {address} -o "{scandir}/recon/dns_sublist3r_{address}.txt"'
        pattern = '^(?P<domain>[a-zA-Z0-9.-]+)(?P<ipaddress>)'

    #[domain.amass-subdomains]
    #    command = '/usr/bin/amass enum -dns-qps 500 -timeout 20 -d {address} -nocolor -demo -o "{scandir}/recon/dns_amass_{address}.txt"'
    #    pattern = '^(?P<domain>[a-zA-Z0-9.-]+)(\s*)(.*)(\s*)(-->\s*)(.*)(\s*)(-->\s*)(?P<ipaddress>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
    
    [domain.fierce-subdomains]
        command = '/usr/bin/fierce --domain {address} | tee "{scandir}/recon/dns_fierce_{address}.ansi"'
        pattern = '^Found:\s*(?P<domain>[\w.-]+)\.\s*\((?P<ipaddress>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\)$'
        
    [domain.cloud-enumeration]
        command = '/usr/bin/cloud_enum --keyword {address} --format csv --logfile "{scandir}/info/cloud_cloudenum_{address}.csv" | tee -a "{scandir}/recon/cloud_cloudenum_{address}.ansi"'
        pattern = '^(?P<domain>(?![\d.]+)((?!-))(xn--)?[a-z0-9][a-z0-9-_]{0,61}[a-z0-9]{0,1}\.(xn--)?([a-z0-9\._-]{1,61}|[a-z0-9-]{1,30}))(?P<ipaddress>)'
    
    [domain.spiderfoot-cloudS3]
        command = '/usr/bin/spiderfoot -m sfp_s3bucket -q -r -s {address} | tee -a "{scandir}/recon/cloud_spiderfoot_{address}.ansi"'
        pattern = '(.*)(IP)(\s*)(Address)(\s*)(?P<domain>[a-zA-Z0-9.-]+)(\s*)(?P<ipaddress>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'

[ipaddress]
    [ipaddress.amass-revlookup]
        command = '/usr/bin/amass intel -v -max-dns-queries 500 -timeout 10 -cidr {address} -o "{scandir}/recon/revlook_amass_{address}.txt"'
        pattern = '(.*)(\\t)(IP)(\s*)(Address)(\\t)(?P<domain>(?![\d.]+)((?!-))(xn--)?[a-z0-9][a-z0-9-_]{0,61}[a-z0-9]{0,1}\.(xn--)?([a-z0-9\._-]{1,61}|[a-z0-9-]{1,30})(\\t)(?P<ipaddress>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))'

    [ipaddress.spiderfoot-revlookup]
        command = '/usr/bin/spiderfoot -t CO_HOSTED_SITE_DOMAIN,CO_HOSTED_SITE,CO_HOSTED_SITE_DOMAIN_WHOIS,INTERNET_NAME,INTERNET_NAME_UNRESOLVED,DOMAIN_NAME,PROVIDER_DNS,PROVIDER_HOSTING,PROVIDER_MAIL,PROVIDER_TELCO -f -q -r -s {address} -o csv | tee "{scandir}/recon/revlookup_spiderfoot_{address}.ansi"'
        pattern = '.*(,)(?P<ipaddress>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})(,)(?P<domain>[a-zA-Z0-9.-]+)$'

#[default.dnsrecon-revlookup]
#    [default.dnsrecon-revlookup.ipaddress]
#    command = '/usr/bin/dnsrecon -r {address} -c "{scandir}/_revlookup_dnsrecon_{address}.csv"'
#    pattern = '(.*)(\\t)(IP)(\s*)(Address)(\\t)(?P<domain>(?![\d.]+)((?!-))(xn--)?[a-z0-9][a-z0-9-_]{0,61}[a-z0-9]{0,1}\.(xn--)?([a-z0-9\._-]{1,61}|[a-z0-9-]{1,30})(\\t)(?P<ipaddress>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}))'
